version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: net.sf.saxon:Saxon-HE
        versions:
          - '>= 10'
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
