[[sec:tran-rules4]]
== Transformation of UML descriptors

In this section are specified transformation rules for UML descriptive elements. <<tab:descriptiors-overview>> provides an overview of the section coverage.

[[tab:descriptiors-overview]]
.Overview of transformation rules for UML descriptors
[cols="<,<,<,<",options="header",]
|===
|UML element |Rules in core ontology layer |Rules in data shape layer |Rules in reasoning layer
|Name |<<rule:elemen-label>> |<<rule:elemen-label>> |<<rule:elemen-label>>
|Note |<<rule:elemen-definition>> |<<rule:elemen-definition>> |<<rule:elemen-definition>>
|Comment |<<rule:elemen-external-comment>> |<<rule:elemen-external-comment>> |<<rule:elemen-external-comment>>
|===

=== Name

Most of the UML elements are named. The UML conventions dedicate an extensive section to the naming conventions and how deterministically to generate an URI and a label from the UML element name. The label should be associated to the resource URI by `rdfs:label` and, even if redundant, also as `skos:prefLabel`.

[#rule:elemen-label,source,XML,caption='',title='{example-caption} {counter:rule-cnt:T.01}. Label',reftext='{example-caption} {rule-cnt}']
====
Specify a label for UML element.
====

[cols="a,a", options="noheader"]
|===
|
.Labels in Turtle syntax
[source,Turtle]
----
:ResourceName
  rdfs:label "Resource name" ;
  skos:prefLabel "Resource name"@en ;
.
----
|
.Labels in RDF/XML syntax
[source,XML]
----
<rdf:Description rdf:about="http://base.uri/ResourceName">
  <rdfs:label>Resource name</rdfs:label>
  <skos:prefLabel xml:lang="en">Resource name</skos:prefLabel>
</rdf:Description>
----
|===

=== Note

Most of the UML element foresee provisions of descriptions and notes. They should be transformed into `rdfs:comment` and `skos:definition`.

[#rule:elemen-definition,source,XML,caption='',title='{example-caption} {counter:rule-cnt:D.1}. Description',reftext='{example-caption} {rule-cnt}']
====
Specify a description for UML element.
====

[cols="a,a", options="noheader"]
|===
|
.Description in Turtle syntax
[source,Turtle]
----
:ResourceName
  rdfs:comment "Description of teh resource meaning" ;
  skos:definition "Resource name"@en ;
.
----
|
.Description in RDF/XML syntax
[source,XML]
----
<rdf:Description rdf:about="http://base.uri/ResourceName">
  <rdfs:comment>Description of teh resource meaning</rdfs:comment>
  <skos:definition xml:lang="en">Description of teh resource meaning</skos:definition>
</rdf:Description>
----
|===

=== Comment

In accordance with , every kind of UML Element may own Comments (see Figure #fig:comment-visual[1]). They add no semantics but may represent information useful to the reader. In OWL it is possible to define the annotation axiom for OWL Class, Datatype, ObjectProperty, DataProperty, AnnotationProperty and NamedIndividual. The textual explanation added to UML Class is identified as useful for conceptual modelling , therefore the Comments that are connected to UML Classes are taken into consideration in the transformation.

As UML Comments add no semantics, they are not used in any method of semantic validation. In OWL the AnnotationAssertion axiom does not add any semantics either, and it only improves readability.

[#rule:elemen-external-comment,source,XML,caption='',title='{example-caption} {counter:rule-cnt:D.1}. Comment',reftext='{example-caption} {rule-cnt}']
====
Specify annotation axiom for UML Comment associated to a UML element.
====

[cols="a,a", options="noheader"]
|===
|
.Comment in Turtle syntax
[source,Turtle]
----
:ClassName
  rdfs:comment "This is an additional comment on ClassName" ;
  skos:editorialNote "This is an additional comment on ClassName"@en ;
.
----
|
.Comment in RDF/XML syntax
[source,XML]
----
<rdf:Description rdf:about="http://base.uri/ClassName">
  <rdfs:comment>This is an additional comment on ClassName</rdfs:comment>
  <skos:editorialNote xml:lang="en">This is an additional comment on ClassName</skos:definition>
</rdf:Description>
----
|===