= The SEMIC Style Guide for Semantic Engineers
:favicon: favicon.gif
:description: The SEMIC Style Guide for Semantic Engineers.
:sectanchors:
:url-repo: https://github.com/SEMICeu/style-guide

This document defines the style guide to be applied to the SEMIC's semantic data specifications, notably to the eGovernment Core Vocabularies and Application Profiles. It provides rules on naming conventions, syntax, artefact management and organisation. It is meant to be complemented with technical artefacts and implementations that enable automatic conformance checking and transformation of conceptual models into formal semantic representations.

The content of these guides is part of the action to promote semantic interoperability amongst the EU Member States, with the objective of fostering the use of standards by, for example, offering guidelines and expert advice on semantic interoperability for public administrations.

This style guide is intended primarily for semantic engineers, data architects and knowledge modelling specialists who are acting as editors or reusers of Core Vocabularies and Application Profiles. 

This style guide may constitute a good source of information and explanations for the European Commission's officers, collaborating consultants, and stakeholders involved in interinstitutional standardisation.
