"""
The module contains tests for an AsciiDoc glossary content.
Testing is based on a comparison of the former HTML glossary,
using a stable version which content has been already verified
in the past. The new AsciiDoc glossary is tested by using
it's HTML version generated by Antora from *.adoc source file.

The module contains three tests testing three glossary tables:
1.1 Class names and definitions
1.2 Attributes (datatype properties) names and definitions
1.3 Predicates (object properties) and definitions

A test extracts a table from the two glossary HTML files
and verifies if the content is the same.

Due to practical reasons, some normalization of the text takes place
before the comparison, to avoid false negatives due to formatting
differences. The normalization process focuses on specific fields
in the glossary tables, such as "Definition", "Data type / cardinality",
and "Domain, Range and Cardinality".
The scope of normalization is further described in the
`normalize_text` function in `functionalTests/utils/glossary.py`.
"""

import json
from typing import Callable

from deepdiff import DeepDiff
import pytest

from functionalTests import (
    ROOT_TEST_DATA_PATH,
    save_on_assert_failure,
)
from functionalTests.utils.glossary import (
    build_index,
    html_table_as_dict,
    extract_table_by_xpath,
    fix_former_glossary_formatting,
    is_attribute_name_shared,
    is_relationship_name_shared,
    normalize_text,
    preprocess_shared_attribute_data,
    preprocess_shared_relationship_data,
)


TEST_SUITE_DATA_DIR = "glossary"
TEST_DATA_PATH = ROOT_TEST_DATA_PATH / TEST_SUITE_DATA_DIR
TEST_OUTPUT_DATA_PATH = TEST_DATA_PATH / ".output"
SAVE_JSON_DATA_FOR_DEBUG = True

if SAVE_JSON_DATA_FOR_DEBUG:
    TEST_OUTPUT_DATA_PATH.mkdir(exist_ok=True)


INPUT_FORMER_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH = (
    TEST_DATA_PATH / "ePO_core_5.0.0-glossary_former-without_reused_concepts.html"
)
INPUT_ASCIIDOC_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH = (
    TEST_DATA_PATH / "ePO_core_5.0.0-glossary_asciidoc-without_reused_concepts.html"
)
INPUT_FORMER_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH = (
    TEST_DATA_PATH / "ePO_core_5.0.0-glossary_former-with_reused_concepts.html"
)
INPUT_ASCIIDOC_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH = (
    TEST_DATA_PATH / "ePO_core_5.0.0-glossary_asciidoc-with_reused_concepts.html"
)

# This refers to a row in predicates table where the
# value for the "Domain, Range and Cardinality" column is missing
KNOWN_ISSUE_IN_FORMER_RELS_TABLE_ROW_KEY = "epo:hasDocumentType"


def build_debug_file_path(request, data_signature="", ext="json") -> str:
    return (
        TEST_OUTPUT_DATA_PATH
        / f"{request.node.callspec.id}{'_' + data_signature if data_signature else ''}.{ext}"
    )


@pytest.fixture
def input_former_glossary_file_path():
    return TEST_DATA_PATH / "ePO_core_glossary-former.html"


@pytest.fixture
def input_asciidoc_glossary_file_path():
    return TEST_DATA_PATH / "ePO_core_glossary-asciidoc.html"


def get_cleaned_table_data(
    html_file_path, table_xpath, fix_format: bool = False, **kwargs
) -> dict:
    table_html = extract_table_by_xpath(html_file_path, table_xpath)
    table_data = html_table_as_dict(table_html, **kwargs)
    if fix_format:
        table_data = fix_former_glossary_formatting(table_data)
    data = normalize_text(
        table_data,
        keys=["Definition", "Data type / cardinality", "Domain, Range and Cardinality"],
    )
    if SAVE_JSON_DATA_FOR_DEBUG:
        debug_file_path = TEST_OUTPUT_DATA_PATH / str(
            html_file_path.name + table_xpath.replace("/", "_") + ".json"
        )
        with open(debug_file_path, "w") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    return data


###################### Fixtures for glossary tables data ######################


@pytest.fixture
def former_gloss_classes_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[1]"
    return get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Class name",
    )


@pytest.fixture
def former_gloss_classes_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[1]"
    return get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Class name",
    )


@pytest.fixture
def asciidoc_gloss_classes_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[1]/div/table"
    return get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Class name",
    )


@pytest.fixture
def asciidoc_gloss_classes_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[1]/div/table"
    return get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Class name",
    )


@pytest.fixture
def former_gloss_attrs_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[2]"
    return get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Attribute name",
    )


@pytest.fixture
def former_gloss_attrs_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[2]"
    return get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Attribute name",
    )


@pytest.fixture
def asciidoc_gloss_attrs_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[2]/div/table"
    return get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Attribute name",
    )


@pytest.fixture
def asciidoc_gloss_attrs_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[2]/div/table"
    return get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Attribute name",
    )


@pytest.fixture
def former_gloss_rels_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[3]"
    data = get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Predicate name",
    )
    # exclude data for a row that has a known issue in the former glossary
    data = [
        r
        for r in data
        if r.get("Predicate name") != KNOWN_ISSUE_IN_FORMER_RELS_TABLE_ROW_KEY
    ]
    return data


@pytest.fixture
def former_gloss_rels_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/main/div[2]/table[3]"
    return get_cleaned_table_data(
        INPUT_FORMER_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        fix_format=True,
        order_by="Predicate name",
    )


@pytest.fixture
def asciidoc_gloss_rels_data_wo_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[3]/div/table"
    data = get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WO_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Predicate name",
    )
    # exclude data for a row that has a known issue in the former glossary
    data = [
        r
        for r in data
        if r.get("Predicate name") != KNOWN_ISSUE_IN_FORMER_RELS_TABLE_ROW_KEY
    ]
    return data


@pytest.fixture
def asciidoc_gloss_rels_data_with_reused_concepts() -> dict:
    table_xpath = "/html/body/div/main/div[2]/article/div[3]/div/table"
    data = get_cleaned_table_data(
        INPUT_ASCIIDOC_GLOSSARY_WITH_REUSED_CONCEPTS_FILE_PATH,
        table_xpath,
        order_by="Predicate name",
    )
    return data


@pytest.fixture
def former_glossary_table_data(request):
    return request.getfixturevalue(request.param)


@pytest.fixture
def asciidoc_glossary_table_data(request):
    return request.getfixturevalue(request.param)


################################## tests #######################################


@pytest.mark.parametrize(
    "former_glossary_table_data,asciidoc_glossary_table_data",
    [
        (
            "former_gloss_classes_data_wo_reused_concepts",
            "asciidoc_gloss_classes_data_wo_reused_concepts",
        ),
        (
            "former_gloss_classes_data_with_reused_concepts",
            "asciidoc_gloss_classes_data_with_reused_concepts",
        ),
    ],
    indirect=True,
)
def test_compare_classes_for_two_glossary_versions(
    former_glossary_table_data: dict,
    asciidoc_glossary_table_data: dict,
):
    """
    Compares glossary table entries for classes.

    This test checks the AsciiDoc glossary content against the former HTML
    glossary by extracting and normalizing relevant table data from both
    sources. The test checks if values of the table cells for the same
    properties match.
    """
    diff = DeepDiff(
        former_glossary_table_data,
        asciidoc_glossary_table_data,
        ignore_order=True,
        report_repetition=True,
        verbose_level=2,
    ).pretty()
    print(diff)
    assert (
        not diff
    ), f"The AsciiDoc glossary does not match the former HTML version: {diff}"


@pytest.mark.parametrize(
    "former_glossary_table_data,asciidoc_glossary_table_data,filter_func",
    [
        (
            "former_gloss_attrs_data_with_reused_concepts",
            "asciidoc_gloss_attrs_data_with_reused_concepts",
            lambda a: not is_attribute_name_shared(a),
        ),
        (
            "former_gloss_attrs_data_wo_reused_concepts",
            "asciidoc_gloss_attrs_data_wo_reused_concepts",
            lambda a: not is_attribute_name_shared(a),
        ),
        (
            "former_gloss_rels_data_with_reused_concepts",
            "asciidoc_gloss_rels_data_with_reused_concepts",
            lambda r: not is_relationship_name_shared(r),
        ),
        (
            "former_gloss_rels_data_wo_reused_concepts",
            "asciidoc_gloss_rels_data_wo_reused_concepts",
            lambda r: not is_relationship_name_shared(r),
        ),
    ],
    indirect=["former_glossary_table_data", "asciidoc_glossary_table_data"],
)
def test_compare_unique_properties_for_two_glossary_versions(
    former_glossary_table_data: dict,
    asciidoc_glossary_table_data: dict,
    filter_func: Callable,
):
    """
    Compares glossary table entries for attributes and relationships
    (predicates) whose names are not reused across multiple classes or
    relations.

    This test checks the AsciiDoc glossary content against the former HTML
    glossary by extracting and normalizing relevant table data from both
    sources.
    The test checks if values of the table cells for the same properties match.
    """
    try:
        diff = DeepDiff(
            [r for r in former_glossary_table_data if filter_func(r)],
            [r for r in asciidoc_glossary_table_data if filter_func(r)],
            ignore_order=True,
            report_repetition=True,
            verbose_level=2,
        )
        diff_str = diff.pretty()
        print()
        assert (
            not diff_str
        ), f"The AsciiDoc glossary does not match the former HTML version: {diff_str}"
    except AssertionError:
        # ignore any differences caused due to different spacing
        matching = []
        for k, v in diff["values_changed"].items():
            if v["new_value"].replace(" ", "") == v["old_value"].replace(" ", ""):
                matching.append(k)
        for k in matching:
            diff["values_changed"].pop(k, None)
        if diff["values_changed"]:
            raise  # raises the original error if at least one difference remains


@pytest.mark.parametrize(
    "former_glossary_table_data,asciidoc_glossary_table_data,filter_func,preprocess_func",
    [
        (
            "former_gloss_attrs_data_with_reused_concepts",
            "asciidoc_gloss_attrs_data_with_reused_concepts",
            is_attribute_name_shared,
            preprocess_shared_attribute_data,
        ),
        (
            "former_gloss_attrs_data_wo_reused_concepts",
            "asciidoc_gloss_attrs_data_wo_reused_concepts",
            is_attribute_name_shared,
            preprocess_shared_attribute_data,
        ),
        (
            "former_gloss_rels_data_with_reused_concepts",
            "asciidoc_gloss_rels_data_with_reused_concepts",
            is_relationship_name_shared,
            preprocess_shared_relationship_data,
        ),
        (
            "former_gloss_rels_data_wo_reused_concepts",
            "asciidoc_gloss_rels_data_wo_reused_concepts",
            is_relationship_name_shared,
            preprocess_shared_relationship_data,
        ),
    ],
    indirect=["former_glossary_table_data", "asciidoc_glossary_table_data"],
)
def test_compare_shared_properties_for_two_glossary_versions(
    former_glossary_table_data: dict,
    asciidoc_glossary_table_data: dict,
    filter_func: Callable,
    preprocess_func: Callable,
    request,
):
    """
    Compares glossary table entries for attributes and relationships
    (predicates) whose names are reused across multiple classes or relations.

    This test checks the AsciiDoc glossary content against the former HTML
    glossary by extracting and normalizing relevant table data from both
    sources.
    The test checks if values of the table cells for the same properties match.
    Testing of definitions is handled differently due to repetitions in the
    former glossary.
    """
    expected = [
        preprocess_func(r) for r in former_glossary_table_data if filter_func(r)
    ]
    actual = [
        preprocess_func(r) for r in asciidoc_glossary_table_data if filter_func(r)
    ]
    diff = DeepDiff(
        expected, actual, ignore_order=True, report_repetition=True, verbose_level=2
    ).pretty()
    print(diff)
    with save_on_assert_failure(
        SAVE_JSON_DATA_FOR_DEBUG,
        build_debug_file_path(request, "former"),
        expected,
        build_debug_file_path(request, "asciidoc"),
        actual,
    ):
        assert (
            not diff
        ), f"The AsciiDoc glossary does not match the former HTML version: {diff}"

    # Handle definitions separately

    # key used to identify and index entries
    key = (
        "Attribute name"
        if "Attribute name" in former_glossary_table_data[0]
        else "Predicate name"
    )
    asciidoc_glossary_table_data_idx = build_index(asciidoc_glossary_table_data, key)

    for r in former_glossary_table_data:
        asciidoc_gloss_def = asciidoc_glossary_table_data_idx[r[key]]["Definition"]
        expected_def = r["Definition"]
        # need to remove spaces for comparision due to formatting differences
        # caused by invalid concatenation in the former glossary
        assert asciidoc_gloss_def.replace(" ", "") in expected_def.replace(" ", ""), (
            f"The definition for '{r[key]}' does not match: "
            f"expected '{expected_def}', got '{asciidoc_gloss_def}'"
        )
