branches:
  except:
    - schxslt

skip_tags: true

skip_branch_with_pr: true

environment:
  matrix:
    # Non-mainstream jobs are not included in favor of GitHub Actions and Azure Pipelines
    - XSPEC_TEST_ENV: saxon-9-9

install:
  - cmd: test\ci\install-deps.cmd

build: off

test_script:
  - cmd: |
      test\ci\print-env.cmd
      test\ci\run-core-tests.cmd
      test\ci\maven-package.cmd -q
      test\ci\compile-java.cmd -silent
      test\ci\last-git-status.cmd
      test\ci\test-maven-jar.cmd -silent

deploy: off
