== Conventions on uml:Enumeration elements

[[sec:enumeration]]
===  Technical conventions on uml:Enumeration elements

In UML the controlled lists, discussed in Section [xref:uml/conv-general.adoc#sec:controlled-list[Controlled List]] are represented as uml:Enumeration. They are transformed into instances of a SKOS model [xref:references.adoc#ref:skos-spec[skos-spec]].


[[sec:enumeration-to-skos]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Interpretation of uml:Enumeration

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*

An uml:Enumeration element is transformed into `skos:ConceptScheme`, and an enumeration item into a `skos:Concept`.
|===

*Description:*


Each uml:Enumeration element is transformed into skos:ConceptScheme, and each enumeration item (represented by an uml:Attribute) is transformed into a skos:Concept. An enumeration must not be empty. [TODO: Is this last sentence still valid? How about in case of Enumerations that refer to external controlled lists? If this is statement is valid, would it make sense to make sense to create a separate rule for it?]

In a uml:Enumeration element, the name shall be interpreted as the controlled list name; it must be a normalised string. Each attribute name is used as a local segment in the generation of the concept URI. The attribute type is ignored and by default is considered to be skos:Concept. The attribute alias is transformed into skos:Concept preferred label. The attribute initial value is transformed into the alternative label of the concept. If the attribute alias is longer than the attribute initial value, then it is considered that the two fields have been swapped by mistake. [TODO: Check whether these assumptions and manipulations are still valid]

In case no attribute alias is specified then the attribute name is used as preferred label of the skos:Concept. This happens as skos:prefLabel is a mandatory property in the SKOS model.

It is possible to employ the enumerations for class properties by drawing a dependency (uml:Dependency) relation from the class to the enumeration and provide a relation target role.
