== UML Connector Elements

[[sec:relations]]
=== Conventional recommendations on Relations


[[rule:connetors-names-with-verb]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Connector names

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Relations are to be expressed through uml:Connector elements. It is recommended to use a verb in the uml:Connector element names.
|===

*Description:*

When establishing relations between concepts it is conventional to use verbs of action, state, process or relation, such as "includes", "replaces", "manages". It is required to use a verb or a verb phrase for relationship terms. It should be in _lowerCamelCase_ such that latexmath:[$<subject-predicate-object>$] triples may actually be read as natural language clauses, e.g. "EconomicOperator offers ProcuredItem" [xref:references.adoc#ref:d2.01-2017[d2.01-2017]].

The verb phrase must be in present tense, if needed inflected as third person singular. If an additional level of specificity is needed a qualifying nominal phrase may be appended.


[[rule:connetors-bidirectional]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Bidirectional relations

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Relationships are usually bidirectional, and the name for both directions should be provided, where it makes sense.
|===

*Description:*

Relationships are usually bidirectional, and the names of the relations in both directions should be provided, where it makes sense from the modeling point of view. Adjust the verb phrases in the predicates as appropriate. Usually, by employing the _active and passive voice_ in the term formulation brings the desired result. For example, "uses/isUsedBy" and "refersTo/isReferredToBy" or "offers/isOfferedBy" [xref:references.adoc#ref:d2.01-2017[d2.01-2017]].


[[rule:connetors-inverse]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Inverse relation

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Semantically inverse relationships should be represented as two distinct uml:Connector elements.
|===

*Description:*

The name of the inverse relation should not be semantically inverted verb, such as in case of "buys/sells" , "open/closes". The semantically inverted dichotomies must be modelled in separate connectors because they represent different relations. For example the dichotomy "buys/sells" should be modelled as two pairs: "buys/isBoughtBy" and "sells/isSoldBy".

When the relation is of different nature, more like an attribute, then prefixing and suffixing techniques can be employed. For example, in the Organization Ontology [xref:references.adoc#ref:org-ontology[org-ontology]], the concepts of an "Organization" and a "Site" are defined along with two relationships that are the inverse of each other: "Organisation hasSite Site" and "Site siteOf Organisation" [xref:references.adoc#ref:d3.1-2015[d3.1-2015]].


[[rule:connetors-inverse-definition]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Definition of inverse relations

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
It is recommended that the definition of both the relation and its inverse relation is provided.
|===

*Description:*

It is recommended that each relationship includes a definition of its inverse.

Models should define such inverse pairs for relationships although this does not extend to attributes. For example, Dublin Core [xref:references.adoc#ref:dublin-core-metadata[dublin-core-metadata]] includes a property of "dateAccepted", there is no inverse property that would link a given date, which is expressed as a simple value, to all the documents accepted for publication on that date.


[[sec:association]]
=== Technical conventions on uml:Association

[[rule:association-btw-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Associations connect classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Association elements connect two uml:Classes.
|===

*Description:*

The uml:Association connectors represent relations between source and target classes. The association connector cannot be used between other kinds of UML elements.


[[rule:association-target]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Association connector name

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Association connector elements shall have either a name or a target role specified .
|===

*Description:*

A generic UML connector may have a name applied to it, and it may have source/target roles specified in addition. This provides flexibility to how the domain knowledge may be expressed in UML, however this freedom increases the level of ambiguity as well. Therefore, we foresee two distinct ways to express properties: using the connector generic name, or using the connector source/target ends.

First, if a connector name is specified then no source or target roles can be provided. The name must be valid as it is used to generate the OWL property URI. The minimum and maximum cardinality of the relation must be specified as target multiplicity. This approach is discouraged.

The second approach, which is the recommended one, is to use the target role to express the property. If the connector has no name then the target role must be specified. Or the converse, if a target role is specified then no connector name can be specified. Optionally a source role may be provided. In this case the relation direction must be changed from "Source->Target" to "Bidirectional". Or conversely, if the connector direction is "Bidirectional" then source and target roles must be provided. No other directions are permitted.


[[rule:association-multiplicity]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Association multiplicity

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Association connector elements shall have their target multiplicity specified. If source role is specified, also their source multiplicity must be specified.
|===

*Description:*

The target and source multiplicity must be specified accordingly indicating the minimum and maximum cardinality.


[[rule:association-definition]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Association definition

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Association connector shall have a definition.
|===

*Description:*

It is recommended that each association has a definition. The definition is then used for each role as they stand for the same meaning manifested in the inverse direction. Additional, specific definition, can be specified along the target and source roles.


[[sec:dependency]]
=== Technical conventions on uml:Dependency


[[rule:dependency-btw-class-and-enum]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Dependency connects classes to enumerations

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Dependency connectors connect a uml:Class element to a uml:Enumeration element.
|===

*Description:*

The dependency connector may be used between uml:Class and uml:Enumeration boxes, oriented from the class towards the enumeration. It indicates the class has an owl:ObjectProperty whose range is a controlled vocabulary. The connector must have direction "Source->Target". No other directions are acceptable.


[[rule:dependency-name]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Dependency connector name

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Dependency connector elements shall have a valid name.
|===

*Description:*

The connector must have a valid name and no source/target roles are acceptable.


[[rule:dependency-multiplicity]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Dependency multiplicity

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Dependency connector elements shall have their target multiplicity specified.
|===

*Description:*

The multiplicity must be specified at the target of the uml:Dependency connector indicating the minimum and maximum cardinality.

In the transformation process, for the reasoning purposes, the range of the property must be expressed as a range restriction using `owl:oneOf` the values from the enumeration Concept scheme. This is also valuable for generating SHACL shapes.


[[sec:genaralization]]
=== Technical conventions on uml:Generalization


[[rule:generalization-btw-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Generalization connects classes and sub-classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Generalization connectors connect a uml:Class element to its superclass uml:Class element.
|===

*Description:*

The uml:Generalization connector signifies a class-subClass relation and is transformed into `rdfs:subClassOf` relation standing between source and target classes.


[[rule:generalization-name]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Generalization connector with no name

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Generalization connector elements shall have no name or a target role specified.
|===

*Description:*

The uml:Generalization connectors must have no name or source/target roles specified in the UML model.


[[rule:connetors-proxy-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Proxy classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
For classes defined in external models proxy uml:Class elements should be defined.
|===

*Description:*

In case a model class should inherit a class from an external model then proxies must be created for those classes. For example, if `Buyer` specialises an `org:Organization`, then a proxy for `org:Organization` must be created in the `org` package.


[[rule:connetors-disjoint-subclasses]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Disjoint subclasses

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Subclasses of the same class, represented by multiple uml:Generalization connectors pointing to the same superclass, are assumed disjoint by default. Exceptions may exist and can be encoded.
|===

*Description:*

In this specification, the subclasses are assumed disjoint by default, unless otherwise specified in the transformations script, or explicitly marked on the generalisation relation with `\<<non-disjoint>>` stereotype. For the converse case the `\<<disjoint>>` stereotype shall be used.



[[rule:connetors-equivalent-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Equivalent classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Equivalent classes can be represented by using stereotypes on the uml:Generalization connectors.
|===

*Description:*

In case two classes are equivalent, then the latexmath:[$<<equivalent>>$] or latexmath:[$<<complete>>$] stereotype should be used as a marker.
