== Conventions on uml:DataType elements


[[sec:datatype]]
=== Technical conventions on uml:Datatype elements

This convention draws the distinction between primitive (or atomic) types (consisting of single literal value) and composite types (consisting of multiple attributes) [xref:references.adoc#ref:isaHandbook2015[isaHandbook2015]]. In fact, the composite datatypes must be defined as classes and handled as such. For example: AmountType, Identifier, Quantity and Measure are to be treated as classes even if conceptually they could be seen as composite data types.

It is recommended to employ the primitive datatypes that are already defined in XSD [xref:references.adoc#ref:xsd1.1-spec[xsd1.1-spec]] and RDF [xref:references.adoc#ref:rdf11[rdf11]], which cover the standard and most common types. Thus definitions of custom data types shall be avoided unless the model really needs them. Such cases are, however, rare.

The data types defined in the UML model (and custom ones) are resolved into their XSD equivalent using the correspondences from the xref:#tab:uml2xsd[] table below. Note that the family of string datatypes is mapped to _rdf:langString_. This means that the instance data should provide a language tag for the textual data indicating how it should be read. This enables multilingual data specification. Also, note that Date is mapped to `xsd:date` and DateTime is mapped to `xsd:dateTime`. However, the `xsd:date` is not included in the OWL2 interpretation and instead a strong preference is expressed fro `xsd:dateTime`. Therefore, it is recommended to follow the OWL2 specification, although the `xsd:date` is a valid datatype in the RDF data and in SPARQL queries.

[[tab:uml2xsd]]
.UML to XSD datatype correspondences
[cols="^,^",options="header",]
|===
|UML |XSD
|Boolean |xsd:boolean
|Float |xsd:float
|Integer |xsd:integer
|Char, Character, String |rdf:langString
|Short |xsd:short
|Long |xsd:long
|Decimal |xsd:decimal
|Date |xsd:date
|DateTime |xsd:dateTime
|===

It is recommended to use OWL 2 compliant XSD and RDF standard data types. They may be useful in indicating a specific data type which is not possible with UML ones. For example making a distinction between a general string (xsd:string) and a literal with a language tag (rdf:langString) or XML encoded ones such as rdf:HTML and rdf:XMLLiteral.

For the model consistency, it is recommended that the proxy data types be defined in the model for the XSDfootnote:[https://www.w3.org/2011/rdf-wg/wiki/XSD_Datatypes] and RDF data typesfootnote:[https://www.w3.org/TR/rdf11-concepts/#section-Datatypes] used in the model. The proxies must follow the standard namespace convention using the "rdf" and "xsd" prefixes.


