[[sec:genaralization]]
== Conventions on uml:Generalization Connectors


[[rule:generalization-btw-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Generalization connects classes and sub-classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Generalization connectors connect a uml:Class element to its superclass uml:Class element.
|===

*Description:*

The uml:Generalization connector signifies a class-subClass relation and is transformed into `rdfs:subClassOf` relation standing between source and target classes.


[[rule:generalization-name]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Generalization connector with no name

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Generalization connectors shall have no name or a target role specified.
|===

*Description:*

The uml:Generalization connectors must have no name (see the xref:uml/conv-connectors.adoc#rule:connectors-name[General convention on connector names]) nor source/target roles specified in the UML model.


[[rule:generalization-proxy-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Proxy classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
For classes defined in external models proxy uml:Class elements should be defined.
|===

*Description:*

In case a model class should inherit a class from an external model then proxies must be created for those classes. For example, if `Buyer` specialises an `org:Organization`, then a proxy for `org:Organization` must be created in the `org` package.


[[rule:generalization-disjoint-subclasses]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Disjoint subclasses

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Subclasses of the same class, represented by multiple uml:Generalization connectors pointing to the same superclass, are assumed disjoint by default. Exceptions may exist and can be encoded.
|===

*Description:*

In this specification, the subclasses are assumed disjoint by default, unless otherwise specified in the transformations script, or explicitly marked on the generalisation relation with `\<<non-disjoint>>` stereotype. For the converse case the `\<<disjoint>>` stereotype shall be used.



[[rule:generalization-equivalent-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Equivalent classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Equivalent classes can be represented by using stereotypes on the uml:Generalization connectors.
|===

*Description:*

In case two classes are equivalent, then the latexmath:[$<<equivalent>>$] or latexmath:[$<<complete>>$] stereotype should be used as a marker.
