== Modeling Relations with UML Connectors

[[sec:relations]]
=== Conventional recommendations on Relations


[[rule:connetors-names-with-verb]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Connector names

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Relations are to be expressed through uml:Connector elements. It is recommended to use a verb in the uml:Connector element names.
|===

*Description:*

When establishing relations between concepts it is conventional to use verbs of action, state, process or relation, such as "includes", "replaces", "manages". It is required to use a verb or a verb phrase for relationship terms. It should be in _lowerCamelCase_ such that latexmath:[$<subject-predicate-object>$] triples may actually be read as natural language clauses, e.g. "EconomicOperator offers ProcuredItem" [xref:references.adoc#ref:d2.01-2017[d2.01-2017]].

The verb phrase must be in present tense, if needed inflected as third person singular. If an additional level of specificity is needed a qualifying nominal phrase may be appended.


[[rule:connetors-bidirectional]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Bidirectional relations

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Relationships are usually bidirectional, and the name for both directions should be provided, where it makes sense.
|===

*Description:*

Relationships are usually bidirectional, and the names of the relations in both directions should be provided, where it makes sense from the modeling point of view. Adjust the verb phrases in the predicates as appropriate. Usually, by employing the _active and passive voice_ in the term formulation brings the desired result. For example, "uses/isUsedBy" and "refersTo/isReferredToBy" or "offers/isOfferedBy" [xref:references.adoc#ref:d2.01-2017[d2.01-2017]].


[[rule:connetors-inverse]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Inverse relation

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
Semantically inverse relationships should be represented as two distinct uml:Connector elements.
|===

*Description:*

The name of the inverse relation should not be semantically inverted verb, such as in case of "buys/sells" , "open/closes". The semantically inverted dichotomies must be modelled in separate connectors because they represent different relations. For example the dichotomy "buys/sells" should be modelled as two pairs: "buys/isBoughtBy" and "sells/isSoldBy".

When the relation is of different nature, more like an attribute, then prefixing and suffixing techniques can be employed. For example, in the Organization Ontology [xref:references.adoc#ref:org-ontology[org-ontology]], the concepts of an "Organization" and a "Site" are defined along with two relationships that are the inverse of each other: "Organisation hasSite Site" and "Site siteOf Organisation" [xref:references.adoc#ref:d3.1-2015[d3.1-2015]].


[[rule:connetors-inverse-definition]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Definition of inverse relations

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
It is recommended that the definition of both the relation and its inverse relation is provided.
|===

*Description:*

It is recommended that each relationship includes a definition of its inverse.

Models should define such inverse pairs for relationships although this does not extend to attributes. For example, Dublin Core [xref:references.adoc#ref:dublin-core-metadata[dublin-core-metadata]] includes a property of "dateAccepted", there is no inverse property that would link a given date, which is expressed as a simple value, to all the documents accepted for publication on that date.


[[sec:relations-reuse]]
=== Reuse of Relations

[[sec:connectors]]
=== Technical conventions on connectors

[[rule:association-btw-classes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* uml:Associations connect classes

|{set:cellbgcolor: #f5f8fc}
*Identifier* -

|*Statement:*
uml:Association elements connect two uml:Classes.
|===

*Description:*

The uml:Association connectors represent relations between source and target classes. The association connector cannot be used between other kinds of UML elements.

