from deepdiff import DeepDiff
from pyld import jsonld
import pytest

from functionalTests import ROOT_TEST_DATA_PATH
from functionalTests.utils.jsonld_context import (
    get_jsonld_data,
    get_jsonld_data_for_test_suite,
    run_model2owl_for_artefact
)


TEST_SUITE_DATA_DIR = "jsonld-context"
TEST_DATA_PATH = ROOT_TEST_DATA_PATH / TEST_SUITE_DATA_DIR
TEST_OUTPUT_DATA_PATH = TEST_DATA_PATH / ".output"


@pytest.fixture
def expected_jsonld_data():
    return get_jsonld_data_for_test_suite(
        TEST_SUITE_DATA_DIR, "expected_test_data.jsonld"
    )

@pytest.fixture
def input_xmi_file_path():
    return ROOT_TEST_DATA_PATH / "ePO-core-4.2.0.xml"

@pytest.fixture
def jsonld_data():
    return get_jsonld_data_for_test_suite(
        TEST_SUITE_DATA_DIR, "ePO_data-compacted.jsonld"
    )

@pytest.fixture
def jsonld_context(input_xmi_file_path, jsonld_context_artefact) -> dict:
    jsonld_path = run_model2owl_for_artefact(
        input_xmi_file_path, 
        jsonld_context_artefact, 
        TEST_OUTPUT_DATA_PATH
    )
    return get_jsonld_data(jsonld_path)


def test_generated_jsonld_context_expands_compacted_data_correctly(
    jsonld_data: dict,
    jsonld_context: dict,
    expected_jsonld_data: dict,
    ):
    """
    Tests the JSON-LD context generated by model2owl by applying it in a JSON-LD
    expansion operation. This function generates the JSON-LD context from the
    input ePO model XMI file, takes compacted test data, applies the context to
    the data, and expands it using the JSON-LD processor. It then verifies that
    the expanded form matches the expected expanded data. The test ensures not
    only that the context is syntactically valid, but also that it correctly
    defines ontology terms so compaction of relevant data results in proper
    expanded data.
    """
    # Given
    jsonld_data_with_context = dict(jsonld_data)
    jsonld_data_with_context["@context"] = jsonld_context

    # When
    expanded = jsonld.expand(jsonld_data_with_context)
    
    # Then
    # verify whether the expanded form matches the expected result
    diff = DeepDiff(
        expanded,
        expected_jsonld_data,
        ignore_order=True,
        report_repetition=True
    ).pretty()
    assert not diff, f"Expanded JSON-LD does not match expected: {diff}"
