<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    exclude-result-prefixes="xs math xd"
    version="3.0">
    <xd:doc scope="stylesheet">
        <xd:desc>
            <xd:p><xd:b>Created on:</xd:b> May 2, 2020</xd:p>
            <xd:p><xd:b>Author:</xd:b> lps</xd:p>
            <xd:p></xd:p>
        </xd:desc>
    </xd:doc>
    
    <xd:doc>
        <xd:desc>The static headder and the title of the report</xd:desc>
    </xd:doc>
    <xsl:template name="title-header">
        <header class="counter-skip">
            <h1 class="title">UML Conventions Comformance Report</h1>
            <h2>[ <xsl:value-of select="format-date(current-date(), 
                '[D01]/[M01]/[Y0001]')"/> ]</h2>
            <!--<h2>[ <xsl:value-of select="tokenize(base-uri(.), '/')[last()]"/> ]</h2>-->
            
            <!-- begin hardcoded author -->
            <div class="authors col-span">
                <div class="author">
                    <div>Publications Office of the European Union</div>
                    <div>Luxembourg</div>
                    <div><a href="https://op.europa.eu">https://op.europa.eu</a></div>
                </div>
            </div>
            <!-- end hardcoded author -->
        </header>
    </xsl:template>
    
    <xd:doc>
        <xd:desc>The static abstract of teh report. This should act the introduction</xd:desc>
    </xd:doc>
    <xsl:template name="abstract">
        <div class="abstract counter-skip">
            <h1>Abstract</h1>
            <p>eProcurement UML model needs to conform to a set of UML conventions described
                <a href="https://github.com/OP-TED/model2owl/blob/master/doc/uml-conventions/uml-conventions.pdf" target="_blank">elsewhere</a>. A conformance checking script was developed to execute tests to the UML
                model and generate errors or warnings when encountered. </p>
            
            <p>This document was automatically generated by the conformance checking script and
                comprises the UML conformance violations.</p>
            
            <p>The organisation of this document is based on major types of UML elements and
                connectors that are employed in the eProcurement conceptual model. They are as
                follows: 
                <em>Classes, Enumerations, Datatypes, Packages, Associations, Dependencies and
                    Generalisations</em>. Each major section lists model items that need correction of errors
                or consideration of warnings.</p>
            
            <!--<h4>Tested:</h4>-->
            <p>The UML model in file <em><xsl:value-of select="tokenize(base-uri(.), '/')[last()]"/></em> 
                was tested <xsl:value-of select="format-dateTime(current-dateTime(), 
                    'at [H01]:[m01] on [MNn] [D], [Y0001]')"/>.</p>
        </div>
    </xsl:template>
    
</xsl:stylesheet>