name: Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      XSPEC_TEST_ENV: ${{ matrix.env }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11]
        env: [saxon-10, saxon-9-9, oxygen]
        exclude:
          - os: macos-latest
            env: saxon-9-9
          - java: 8
            env: oxygen

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu

      - name: Uninstall stale Bats for macOS
        if: runner.os == 'macOS'
        run: test/ci/uninstall-bats-macos.sh

      - name: Run tests for *nix
        if: runner.os != 'Windows'
        run: >
          source test/ci/npm-ci.sh
          && source test/ci/install-deps.sh
          && test/ci/print-env.sh
          && test/ci/run-core-tests.sh
          && test/ci/maven-package.sh -q
          && test/ci/compile-java.sh -silent
          && test/ci/last-git-status.sh
          && test/ci/test-maven-jar.sh -silent

      - name: Run tests for Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: >
          call test\ci\install-deps.cmd
          && call test\ci\print-env.cmd
          && call test\ci\run-core-tests.cmd
          && call test\ci\maven-package.cmd -q
          && call test\ci\compile-java.cmd -silent
          && call test\ci\last-git-status.cmd
          && call test\ci\test-maven-jar.cmd -silent

      - uses: actions/upload-artifact@v3
        if: env.MAVEN_PACKAGE_VERSION != ''
        with:
          name: maven-package_${{ env.MAVEN_PACKAGE_VERSION }}_${{ matrix.os }}_java-${{ matrix.java }}_${{ matrix.env }}
          path: target/xspec-${{ env.MAVEN_PACKAGE_VERSION }}*.*
          if-no-files-found: error
