<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0"
	xmlns:serializer="x-urn:xspec:test:end-to-end:processor:serializer"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<!--
		This stylesheet module helps serialize the test result XML.
	-->

	<!--
		Set of serialization parameters
			The parameters must be in sync with
				XQuery: "declare option output:*" generated by XSPEC_HOME/src/compiler/compile-xquery-tests.xsl
				XSLT:   <xsl:result-document> generated by XSPEC_HOME/src/compiler/compile-xslt-tests.xsl

			TODO: Put @parameter-document="xml-report-serialization-parameters.xml" and remove the
				other parameters after the fix for https://saxonica.plan.io/issues/4599 is made
				available on all the supported versions of Saxon.
	-->
	<xsl:output indent="yes" method="xml" name="serializer:output" />
</xsl:stylesheet>
