name: Copy and Commit

on:
  push:
    branches:
      - feature/SM15-38  # Adjust the branch as needed

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout model2owl repository
        uses: actions/checkout@v2


      - name: first clone
        run: |
          ls -la

      - name: Checkout model2owl validator repository
        uses: actions/checkout@v2
        with:
          repository: meaningfy-ws/model2owl-validator

      - name: second clone
        run: |
          ls -la

      - name: Copy folder to destination repository
        run: |
          pwd
          cp -r model2owl/src model2owl-validator/resources/

      - name: Commit and Push to destination repository
        run: |
          cd model2owl-validator
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Copy src folder from model2owl repository"
          git push origin main  # Adjust the branch as needed