name: Update github model2owl-validator repo

on:
  workflow_dispatch:

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout model2owl repository
        uses: actions/checkout@v2


      - name: Copy folder to destination repository
        run: |
          cd ..
          pwd
          ls -la
          mkdir copied-src-folder
          ls -la
          echo "directory to copy src folder was created"
          cp -r model2owl/src copied-src-folder
          ls -la copied-src-folder
          ls -la copied-src-folder/src

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Checkout model2owl validator repository
        uses: actions/checkout@v2
        with:
          repository: meaningfy-ws/model2owl-validator
          token: ${{ secrets.GIT_USER }}
      - name: second clone
        run: |
          ls -la

      - name: Copy folder to destination repository
        run: |
          pwd
          ls -la
          cd ..
          ls -la
          cp -r copied-src-folder/src model2owl/resources/
          cd model2owl/resources
          ls -la

      - name: Commit and Push to destination repository
        run: |

          git add .
          git commit -m "Copy src folder from model2owl repository"
          git status
          git remote -v
          git push -f https://${{ secrets.GIT_USER }}@github.com/meaningfy-ws/model2owl-validator.git main