name: Copy and Commit

on:
  push:
    branches:
      - feature/SM15-38  # Adjust the branch as needed

jobs:
  copy-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout model2owl repository
        uses: actions/checkout@v2


      - name: Copy folder to destination repository
        run: |
          cd ..
          pwd
          ls -la
          mkdir destination-repo
          ls -la
          cp -r model2owl/src destination-repo

      - name: Checkout model2owl validator repository
        uses: actions/checkout@v2
        with:
          repository: meaningfy-ws/model2owl-validator

      - name: second clone
        run: |
          ls -la

      - name: Copy folder to destination repository
        run: |
          pwd
          ls -la
          cd ..
          ls -la
          cp -r destination-repo/src model2owl/resources/
          cd model2owl/resources
          ls -la

#      - name: Commit and Push to destination repository
#        run: |
#
#          git config --local user.email "action@github.com"
#          git config --local user.name "github-actions"
#          git add .
#          git commit -m "Copy src folder from model2owl repository"
#          git push origin main  # Adjust the branch as needed